# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Prompt Appearence
rand=$[$RANDOM%5]
if [ $rand = 0 ]
then
    prompt cloud \>\> cyan blue
elif [ $rand = 1 ]
then
    prompt cloud \>\> red magenta
elif [ $rand = 2 ]
then
    prompt cloud \>\> black white
elif [ $rand = 3 ]
then
    prompt cloud \>\> cyan magenta
else
    prompt cloud \>\> black yellow
fi

# vi mode
set -o vi

# autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# zsh-autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# zsh-syntax highlighting
source /Users/philliporeggio/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Apple touchbar (zsh-apple-touchbar)
source ~/.zsh/zsh-apple-touchbar/zsh-apple-touchbar.zsh

# - Alias
# Vim
alias v="vim -u ~/.simplevimrc"

# git
alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias gb="git branch"
alias gch="git checkout"
alias gpull="git pull"
alias gpu="git push"
alias gpl="git pull"
alias gpsu="git push --set-upstream origin"
alias glog="git log"

# Commands
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"

# Xcode and iOS Dev
alias xcode='open -a Xcode'
alias xvi='open -a XVim'
alias delete_pods='rm -f Podfile.lock && rm -rf Pods'

# Python
alias venv='source venv/bin/activate' # activate venv
alias initvenv='virtualenv --no-site-packages -p python3 venv' # create venv with no site packages
alias python='python3'

# Web Browsers
alias chrome='open -a "Google Chrome 2"'
alias safari='open -a "Safari"'
alias incognito='~/cmd_line_scripts/open_incognito_safari'
# Mail
alias gmail_personal='open -a /Applications/Google\ Chrome\ 2.app '\''https://mail.google.com/mail/u/0/#inbox'\'''
alias gmail_cornell='open -a Safari '\''https://mail.google.com/mail/u/0/#inbox'\'''

# LEETCODE
alias leett='leetcode test'
alias leetget='leetcode show -gx'

# Dotfiles repo
alias dot='/usr/bin/git --git-dir=/Users/philliporeggio/.cfg/ --work-tree=/Users/philliporeggio'
alias dots='dot status'
alias dotc='dot commit -m'

export PATH="/usr/local/opt/node@8/bin:/anaconda3/bin:/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/texbin:/Users/philliporeggio/.vimpkg/bin"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# opam configuration
test -r /Users/philliporeggio/.opam/opam-init/init.zsh && . /Users/philliporeggio/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
