#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi





# Prompt Uppearence
prompt cloud \>\> cyan blue 

#autojump
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh

# zsh-autosuggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# zsh-syntax highlighting
source /Users/philliporeggio/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Apple touchbar (zsh-apple-touchbar)
source ~/.zsh/zsh-apple-touchbar/zsh-apple-touchbar.zsh

# - Alias
# git
alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias gb="git branch"
alias gch="git checkout"
alias gpsu="git push --set-upstream origin"

# Commands
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"

# Xcode and iOS Dev
alias xcode='open -a Xcode'
alias delete_pods='~/cmd_line_scripts/kill_pods'

# Python 
alias venv='source venv/bin/activate' # activate venv
alias initvenv='virtualenv --no-site-packages -p python3 venv' # create venv with no site packages
alias python='python3'

# Web Browsers
alias chrome='open -a "Google Chrome 2"' 
alias safari='open -a "Safari"'
alias incognito='~/cmd_line_scripts/open_incognito_safari'
# Mail
alias gmail_personal='open -a /Applications/Google\ Chrome\ 2.app '\''https://mail.google.com/mail/u/0/#inbox'\'''
alias gmail_cornell='open -a Safari '\''https://mail.google.com/mail/u/0/#inbox'\'''

# LEETCODE
alias leett='leetcode test'
alias leetget='leetcode show -gx'

# Dotfiles repo
alias dot='/usr/bin/git --git-dir=/Users/philliporeggio/.cfg/ --work-tree=/Users/philliporeggio'

export PATH="/usr/local/opt/node@8/bin:/anaconda3/bin:/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/texbin:/Users/philliporeggio/.vimpkg/bin"
