(deftheme cornell
  "Created 2021-02-21.")

(custom-theme-set-variables
 'cornell
 '(ansi-color-names-vector ["#1D252C" "#D95468" "#8BD49C" "#EBBF83" "#5EC4FF" "#E27E8D" "#70E1E8" "#A0B3C5"]))

(custom-theme-set-faces
 'cornell
 '(bold ((((class color) (min-colors 257)) (:weight bold :foreground nil)) (((class color) (min-colors 256)) (:weight bold :foreground nil)) (((class color) (min-colors 16)) (:weight bold :foreground nil))))
 '(italic ((t (:slant italic))))
 '(bold-italic ((t (:inherit (bold italic)))))
 '(fringe ((((class color) (min-colors 257)) (:inherit default :foreground "#384551")) (((class color) (min-colors 256)) (:inherit default :foreground "#334455")) (((class color) (min-colors 16)) (:inherit default :foreground "brightblack"))))
 '(region ((t (:extend t :background "#2a2a2a" :distant-foreground "#5eb2f2" :foreground "#5eb2f2"))))
 '(highlight ((t (:background "#2a2a2a" :distant-foreground "#5eb2f2" :foreground "#5eb2f2"))))
 '(cursor ((((class color) (min-colors 257)) (:background "#5EC4FF")) (((class color) (min-colors 256)) (:background "#55CCFF")) (((class color) (min-colors 16)) (:background "brightblue"))))
 '(shadow ((t (:foreground "#252936"))))
 '(minibuffer-prompt ((t (:foreground "#7AA1EB"))))
 '(tooltip ((t (:background "#181E24" :foreground "#AAAAAA"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:background "#41505E" :extend t)) (((class color) (min-colors 256)) (:background "#ff6655" :extend t)) (((class color) (min-colors 16)) (:background "red" :extend t))))
 '(lazy-highlight ((t (:background "#151926" :distant-foreground "#00ffff" :foreground "#00ffff" :weight bold))))
 '(match ((t (:background "#151926" :foreground "#11A9EB" :weight bold))))
 '(trailing-whitespace ((t (:background "#10151C"))))
 '(nobreak-space ((t (:inherit default :underline nil))))
 '(vertical-border ((t (:background "#333749" :foreground "#333749"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :underline t :weight bold)) (((class color) (min-colors 256)) (:foreground "#5EC4FF" :underline t :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :underline t :weight bold))))
 '(error ((t (:foreground "#FB8496"))))
 '(warning ((t (:foreground "#5eb2f2"))))
 '(success ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(font-lock-builtin-face ((t (:foreground "#FDDC87"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:background nil :foreground "#5675b0")) (((class color) (min-colors 256)) (:background nil :foreground "#5675b0")) (((class color) (min-colors 16)) (:background nil :foreground "red"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 257)) (:foreground "#345390" :background nil)) (((class color) (min-colors 256)) (:foreground "#345390" :background nil)) (((class color) (min-colors 16)) (:foreground "red" :background nil))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:foreground "#93a1ba" :background nil)) (((class color) (min-colors 256)) (:foreground "#93a1ba" :background nil)) (((class color) (min-colors 16)) (:foreground "red" :background nil))))
 '(font-lock-constant-face ((t (:foreground "#FF8833"))))
 '(font-lock-function-name-face ((t (:foreground "#FB8496"))))
 '(font-lock-keyword-face ((t (:foreground "#FDDC87"))))
 '(font-lock-string-face ((t (:foreground "#7AA1EB"))))
 '(font-lock-type-face ((t (:foreground "#7AA1EB"))))
 '(font-lock-variable-name-face ((t (:foreground "#7AA1EB"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#7AA1EB")) (((class color) (min-colors 256)) (:inherit bold :foreground "#5EC4FF")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:foreground "#FDDC87" :inherit bold)) (((class color) (min-colors 256)) (:foreground "#5EC4FF" :inherit bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :inherit bold))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#FDDC87" :inherit bold)) (((class color) (min-colors 256)) (:foreground "#5EC4FF" :inherit bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :inherit bold))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:inherit bold :foreground "#FDDC87")) (((class color) (min-colors 256)) (:inherit bold :foreground "#FDDC87")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(mode-line ((((class color) (min-colors 257)) (:box nil :foreground nil :background "#1B1E2C")) (((class color) (min-colors 256)) (:box nil :foreground nil :background "black")) (((class color) (min-colors 16)) (:box nil :foreground nil :background "black"))))
 '(mode-line-inactive ((t (:background "#181C2A" :foreground "#333333" :box nil))))
 '(mode-line-emphasis ((t (:foreground "#7AA1EB"))))
 '(mode-line-highlight ((((class color) (min-colors 257)) (:inherit bold :foreground "#FF8833")) (((class color) (min-colors 256)) (:inherit bold :foreground "#FF8833")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightblue"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(header-line ((t (:background "#010517" :distant-foreground "#AAAAAA" :foreground "#AAAAAA"))))
 '(tab-line ((t (:background "#010517" :foreground "#010517"))))
 '(line-number ((((class color) (min-colors 257)) (:inherit default :foreground "#232739" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 256)) (:inherit default :foreground "#232739" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 16)) (:inherit default :foreground "brightblack" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:inherit (hl-line default) :foreground "#5eb2f2" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 256)) (:inherit (hl-line default) :foreground "#5eb2f2" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 16)) (:inherit (hl-line default) :foreground "white" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil))))
 '(compilation-column-number ((t (:inherit font-lock-comment-face))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(compilation-error ((t (:inherit error :weight bold))))
 '(compilation-warning ((t (:inherit warning :slant italic))))
 '(compilation-info ((t (:inherit success))))
 '(compilation-mode-line-exit ((t (:inherit compilation-info))))
 '(compilation-mode-line-fail ((t (:inherit compilation-error))))
 '(custom-button ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :background "#1D252C" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground "#55CCFF" :background nil :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil :box (:line-width 1 :style none)))))
 '(custom-button-unraised ((((class color) (min-colors 257)) (:foreground "#B62D65" :background "#1D252C" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground "#BB2266" :background nil :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground "brightmagenta" :background nil :box (:line-width 1 :style none)))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 257)) (:foreground "#1D252C" :background "#B62D65" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground nil :background "#BB2266" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground nil :background "brightmagenta" :box (:line-width 1 :style none)))))
 '(custom-button-pressed ((((class color) (min-colors 257)) (:foreground "#1D252C" :background "#5EC4FF" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground nil :background "#55CCFF" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground nil :background "brightblue" :box (:line-width 1 :style none)))))
 '(custom-button-mouse ((((class color) (min-colors 257)) (:foreground "#1D252C" :background "#5EC4FF" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground nil :background "#55CCFF" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground nil :background "brightblue" :box (:line-width 1 :style none)))))
 '(custom-variable-button ((((class color) (min-colors 257)) (:foreground "#8BD49C" :underline t)) (((class color) (min-colors 256)) (:foreground "#99bb66" :underline t)) (((class color) (min-colors 16)) (:foreground "green" :underline t))))
 '(custom-saved ((((class color) (min-colors 257)) (:foreground "#8BD49C" :background "#334842" :bold t)) (((class color) (min-colors 256)) (:foreground "#99bb66" :background nil :bold t)) (((class color) (min-colors 16)) (:foreground "green" :background nil :bold t))))
 '(custom-comment ((((class color) (min-colors 257)) (:foreground "#A0B3C5" :background "#28323B")) (((class color) (min-colors 256)) (:foreground "#AABBCC" :background "#223333")) (((class color) (min-colors 16)) (:foreground "white" :background "brightblack"))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(custom-modified ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :background "#2a4456")) (((class color) (min-colors 256)) (:foreground "#55CCFF" :background nil)) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(custom-visibility ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :underline nil)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :underline nil)) (((class color) (min-colors 16)) (:foreground "brightblue" :underline nil))))
 '(custom-group-subtitle ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(custom-set ((((class color) (min-colors 257)) (:foreground "#EBBF83" :background "#1D252C")) (((class color) (min-colors 256)) (:foreground "#EEBB88" :background nil)) (((class color) (min-colors 16)) (:foreground "yellow" :background nil))))
 '(custom-themed ((((class color) (min-colors 257)) (:foreground "#EBBF83" :background "#1D252C")) (((class color) (min-colors 256)) (:foreground "#EEBB88" :background nil)) (((class color) (min-colors 16)) (:foreground "yellow" :background nil))))
 '(custom-invalid ((((class color) (min-colors 257)) (:foreground "#D95468" :background "#422e38")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background nil)) (((class color) (min-colors 16)) (:foreground "red" :background nil))))
 '(custom-variable-obsolete ((((class color) (min-colors 257)) (:foreground "#41505E" :background "#1D252C")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background nil)) (((class color) (min-colors 16)) (:foreground "red" :background nil))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#8BD49C" :background "#334842")) (((class color) (min-colors 256)) (:foreground "#99bb66" :background nil)) (((class color) (min-colors 16)) (:foreground "green" :background nil))))
 '(custom-changed ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :background "#1D252C")) (((class color) (min-colors 256)) (:foreground "#55CCFF" :background nil)) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil))))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(dired-ignored ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :weight bold)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#D98E48" :weight bold)) (((class color) (min-colors 256)) (:foreground "#dd8844" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightred" :weight bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#E27E8D" :weight bold :inverse-video t)) (((class color) (min-colors 256)) (:foreground "#EE7788" :weight bold :inverse-video t)) (((class color) (min-colors 16)) (:foreground "magenta" :weight bold :inverse-video t))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#A0B3C5" :underline t)) (((class color) (min-colors 256)) (:foreground "#AABBCC" :underline t)) (((class color) (min-colors 16)) (:foreground "white" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#70E1E8" :weight bold)) (((class color) (min-colors 256)) (:foreground "#77EEEE" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightcyan" :weight bold))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(hl-line ((t (:extend t :background "#252936"))))
 '(isearch ((t (:inherit lazy-highlight :weight bold))))
 '(isearch-fail ((((class color) (min-colors 257)) (:background "#D95468" :foreground "#10151C" :weight bold)) (((class color) (min-colors 256)) (:background "#ff6655" :foreground "black" :weight bold)) (((class color) (min-colors 16)) (:background "red" :foreground "black" :weight bold))))
 '(message-header-name ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(message-header-subject ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :weight bold)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(message-header-to ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :weight bold)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 257)) (:inherit message-header-to :foreground "#4fa6d8")) (((class color) (min-colors 256)) (:inherit message-header-to :foreground "#48add8")) (((class color) (min-colors 16)) (:inherit message-header-to :foreground "brightblue"))))
 '(message-header-other ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(message-header-newsgroups ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(message-header-xheader ((((class color) (min-colors 257)) (:foreground "#707b86")) (((class color) (min-colors 256)) (:foreground "#ff8c7f")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(message-separator ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(message-mml ((((class color) (min-colors 257)) (:foreground "#41505E" :slant italic)) (((class color) (min-colors 256)) (:foreground "#ff6655" :slant italic)) (((class color) (min-colors 16)) (:foreground "red" :slant italic))))
 '(message-cited-text-1 ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(widget-button-pressed ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(widget-documentation ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(window-divider ((t (:inherit vertical-border))))
 '(window-divider-first-pixel ((t (:inherit window-divider))))
 '(window-divider-last-pixel ((t (:inherit window-divider))))
 '(all-the-icons-red ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(all-the-icons-lred ((((class color) (min-colors 257)) (:foreground "#e48795")) (((class color) (min-colors 256)) (:foreground "#ff9388")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(all-the-icons-dred ((((class color) (min-colors 257)) (:foreground "#973a48")) (((class color) (min-colors 256)) (:foreground "#b2473b")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(all-the-icons-green ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(all-the-icons-lgreen ((((class color) (min-colors 257)) (:foreground "#ade0b9")) (((class color) (min-colors 256)) (:foreground "#b7cf93")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(all-the-icons-dgreen ((((class color) (min-colors 257)) (:foreground "#61946d")) (((class color) (min-colors 256)) (:foreground "#6b8247")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(all-the-icons-yellow ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(all-the-icons-lyellow ((((class color) (min-colors 257)) (:foreground "#f1d2a8")) (((class color) (min-colors 256)) (:foreground "#f3cfab")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(all-the-icons-dyellow ((((class color) (min-colors 257)) (:foreground "#a4855b")) (((class color) (min-colors 256)) (:foreground "#a6825f")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(all-the-icons-blue ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(all-the-icons-blue-alt ((((class color) (min-colors 257)) (:foreground "#33CED8")) (((class color) (min-colors 256)) (:foreground "#33CCDD")) (((class color) (min-colors 16)) (:foreground "brightgreen"))))
 '(all-the-icons-lblue ((((class color) (min-colors 257)) (:foreground "#8ed5ff")) (((class color) (min-colors 256)) (:foreground "#88dbff")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(all-the-icons-dblue ((((class color) (min-colors 257)) (:foreground "#718CA1")) (((class color) (min-colors 256)) (:foreground "#7788AA")) (((class color) (min-colors 16)) (:foreground "blue"))))
 '(all-the-icons-maroon ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(all-the-icons-lmaroon ((((class color) (min-colors 257)) (:foreground "#eaa4af")) (((class color) (min-colors 256)) (:foreground "#f39fab")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(all-the-icons-dmaroon ((((class color) (min-colors 257)) (:foreground "#9e5862")) (((class color) (min-colors 256)) (:foreground "#a6535f")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(all-the-icons-purple ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(all-the-icons-lpurple ((((class color) (min-colors 257)) (:foreground "#cb6c93")) (((class color) (min-colors 256)) (:foreground "#cf6493")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(all-the-icons-dpurple ((((class color) (min-colors 257)) (:foreground "#7f1f46")) (((class color) (min-colors 256)) (:foreground "#821747")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(all-the-icons-cyan ((((class color) (min-colors 257)) (:foreground "#70E1E8")) (((class color) (min-colors 256)) (:foreground "#77EEEE")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(all-the-icons-cyan-alt ((((class color) (min-colors 257)) (:foreground "#70E1E8")) (((class color) (min-colors 256)) (:foreground "#77EEEE")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(all-the-icons-lcyan ((((class color) (min-colors 257)) (:foreground "#9aeaee")) (((class color) (min-colors 256)) (:foreground "#9ff3f3")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(all-the-icons-dcyan ((((class color) (min-colors 257)) (:foreground "#008B94")) (((class color) (min-colors 256)) (:foreground "#008899")) (((class color) (min-colors 16)) (:foreground "cyan"))))
 '(all-the-icons-pink ((((class color) (min-colors 257)) (:foreground "#e68f9c")) (((class color) (min-colors 256)) (:foreground "#ff9b90")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(all-the-icons-lpink ((((class color) (min-colors 257)) (:foreground "#edb2bb")) (((class color) (min-colors 256)) (:foreground "#ffbab2")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(all-the-icons-dpink ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(all-the-icons-silver ((((class color) (min-colors 257)) (:foreground "#969ea6")) (((class color) (min-colors 256)) (:foreground "#ffaaa1")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(all-the-icons-lsilver ((((class color) (min-colors 257)) (:foreground "#c5cace")) (((class color) (min-colors 256)) (:foreground "#ffd1cb")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(all-the-icons-dsilver ((((class color) (min-colors 257)) (:foreground "#53616e")) (((class color) (min-colors 256)) (:foreground "#ff7565")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(anzu-replace-highlight ((((class color) (min-colors 257)) (:background "#10151C" :foreground "#D95468" :weight bold :strike-through t)) (((class color) (min-colors 256)) (:background "black" :foreground "#ff6655" :weight bold :strike-through t)) (((class color) (min-colors 16)) (:background "black" :foreground "red" :weight bold :strike-through t))))
 '(anzu-replace-to ((((class color) (min-colors 257)) (:background "#10151C" :foreground "#8BD49C" :weight bold)) (((class color) (min-colors 256)) (:background "black" :foreground "#99bb66" :weight bold)) (((class color) (min-colors 16)) (:background "black" :foreground "green" :weight bold))))
 '(avy-background-face ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(avy-lead-face ((t (:distant-foreground "#00ffff" :foreground "#00ffff" :weight bold))))
 '(avy-lead-face-0 ((((class color) (min-colors 257) (background dark)) (:foreground "#8EB4ee" :inherit avy-lead-face)) (((class color) (min-colors 256) (background dark)) (:foreground "#8EB4ee" :inherit avy-lead-face)) (((class color) (min-colors 16) (background dark)) (:foreground "#8EB4ee" :inherit avy-lead-face)) (((class color) (min-colors 257) (background light)) (:foreground "#8EB4ee" :inherit avy-lead-face)) (((class color) (min-colors 256) (background light)) (:foreground "#8EB4ee" :inherit avy-lead-face)) (((class color) (min-colors 16) (background light)) (:foreground "lightblue" :inherit avy-lead-face))))
 '(avy-lead-face-1 ((((class color) (min-colors 257) (background dark)) (:inherit avy-lead-face :foreground "#7EC4CC")) (((class color) (min-colors 256) (background dark)) (:inherit avy-lead-face :foreground "#7EC4CC")) (((class color) (min-colors 16) (background dark)) (:inherit avy-lead-face :foreground "#7EC4CC")) (((class color) (min-colors 257) (background light)) (:inherit avy-lead-face :foreground "#7EC4CC")) (((class color) (min-colors 256) (background light)) (:inherit avy-lead-face :foreground "#7EC4CC")) (((class color) (min-colors 16) (background light)) (:inherit avy-lead-face :foreground "blue"))))
 '(avy-lead-face-2 ((((class color) (min-colors 257) (background dark)) (:inherit avy-lead-face :foreground "#9EB4BB")) (((class color) (min-colors 256) (background dark)) (:inherit avy-lead-face :foreground "#9EB4BB")) (((class color) (min-colors 16) (background dark)) (:inherit avy-lead-face :foreground "#9EB4BB")) (((class color) (min-colors 257) (background light)) (:inherit avy-lead-face :foreground "#9EB4BB")) (((class color) (min-colors 256) (background light)) (:inherit avy-lead-face :foreground "#9EB4BB")) (((class color) (min-colors 16) (background light)) (:inherit avy-lead-face :foreground "gray"))))
 '(company-tooltip-common ((t (:distant-foreground "#10151C" :foreground "#A6C3F6" :weight bold))))
 '(company-tooltip-search ((((class color) (min-colors 257)) (:background "#5EC4FF" :foreground "#1D252C" :distant-foreground "#A0B3C5" :weight bold)) (((class color) (min-colors 256)) (:background "#55CCFF" :foreground nil :distant-foreground "#AABBCC" :weight bold)) (((class color) (min-colors 16)) (:background "brightblue" :foreground nil :distant-foreground "white" :weight bold))))
 '(company-tooltip-search-selection ((t (:background "#546978"))))
 '(company-tooltip-selection ((t (:background "#353956"))))
 '(company-tooltip-mouse ((((class color) (min-colors 257)) (:background "#E27E8D" :foreground "#1D252C" :distant-foreground "#A0B3C5")) (((class color) (min-colors 256)) (:background "#EE7788" :foreground nil :distant-foreground "#AABBCC")) (((class color) (min-colors 16)) (:background "magenta" :foreground nil :distant-foreground "white"))))
 '(company-tooltip-annotation ((((class color) (min-colors 257)) (:foreground "#B62D65" :distant-foreground "#1D252C")) (((class color) (min-colors 256)) (:foreground "#BB2266" :distant-foreground nil)) (((class color) (min-colors 16)) (:foreground "brightmagenta" :distant-foreground nil))))
 '(company-scrollbar-bg ((t (:inherit tooltip))))
 '(company-scrollbar-fg ((((class color) (min-colors 257)) (:background "#5EC4FF")) (((class color) (min-colors 256)) (:background "#55CCFF")) (((class color) (min-colors 16)) (:background "brightblue"))))
 '(company-preview ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(company-preview-common ((((class color) (min-colors 257)) (:background "#28323B" :foreground "#5EC4FF")) (((class color) (min-colors 256)) (:background "#223333" :foreground "#55CCFF")) (((class color) (min-colors 16)) (:background "brightblack" :foreground "brightblue"))))
 '(company-preview-search ((t (:inherit company-tooltip-search))))
 '(company-tooltip ((t (:foreground "#A0B3C5"))))
 '(diff-hl-change ((((class color) (min-colors 257)) (:foreground "#D98E48" :background "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844" :background "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred" :background "brightred"))))
 '(diff-hl-delete ((((class color) (min-colors 257)) (:foreground "#D95468" :background "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "#ff6655")) (((class color) (min-colors 16)) (:foreground "red" :background "red"))))
 '(diff-hl-insert ((((class color) (min-colors 257)) (:foreground "#8BD49C" :background "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66" :background "#99bb66")) (((class color) (min-colors 16)) (:foreground "green" :background "green"))))
 '(diff-added ((((class color) (min-colors 257)) (:inherit hl-line :foreground "#8BD49C")) (((class color) (min-colors 256)) (:inherit hl-line :foreground "#99bb66")) (((class color) (min-colors 16)) (:inherit hl-line :foreground "green"))))
 '(diff-changed ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(diff-context ((((class color) (min-colors 257) (background dark)) (:foreground "#8c9dad")) (((class color) (min-colors 256) (background dark)) (:foreground "#95a4b3")) (((class color) (min-colors 16) (background dark)) (:foreground "white")) (((class color) (min-colors 257) (background light)) (:foreground "#abbccb")) (((class color) (min-colors 256) (background light)) (:foreground "#b4c3d2")) (((class color) (min-colors 16) (background light)) (:foreground "white"))))
 '(diff-removed ((((class color) (min-colors 257)) (:foreground "#D95468" :background "#28323B")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "#223333")) (((class color) (min-colors 16)) (:foreground "red" :background "brightblack"))))
 '(diff-header ((((class color) (min-colors 257)) (:foreground "#70E1E8" :background nil)) (((class color) (min-colors 256)) (:foreground "#77EEEE" :background nil)) (((class color) (min-colors 16)) (:foreground "brightcyan" :background nil))))
 '(diff-file-header ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :background nil)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :background nil)) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(diff-refine-added ((t (:inherit diff-added :inverse-video t))))
 '(diff-refine-changed ((t (:inherit diff-changed :inverse-video t))))
 '(diff-refine-removed ((t (:inherit diff-removed :inverse-video t))))
 '(diredfl-autofile-name ((((class color) (min-colors 257)) (:foreground "#384551")) (((class color) (min-colors 256)) (:foreground "#334455")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(diredfl-compressed-file-name ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(diredfl-compressed-file-suffix ((((class color) (min-colors 257)) (:foreground "#8d643c")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(diredfl-date-time ((((class color) (min-colors 257)) (:foreground "#70E1E8" :weight light)) (((class color) (min-colors 256)) (:foreground "#77EEEE" :weight light)) (((class color) (min-colors 16)) (:foreground "brightcyan" :weight light))))
 '(diredfl-deletion ((((class color) (min-colors 257)) (:foreground "#D95468" :background "#422e38" :weight bold)) (((class color) (min-colors 256)) (:foreground "#ff6655" :background nil :weight bold)) (((class color) (min-colors 16)) (:foreground "red" :background nil :weight bold))))
 '(diredfl-deletion-file-name ((((class color) (min-colors 257)) (:foreground "#D95468" :background "#422e38")) (((class color) (min-colors 256)) (:foreground "#ff6655" :background nil)) (((class color) (min-colors 16)) (:foreground "red" :background nil))))
 '(diredfl-dir-heading ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :weight bold)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(diredfl-dir-name ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(diredfl-dir-priv ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(diredfl-exec-priv ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(diredfl-executable-tag ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(diredfl-file-name ((((class color) (min-colors 257)) (:foreground "#A0B3C5")) (((class color) (min-colors 256)) (:foreground "#AABBCC")) (((class color) (min-colors 16)) (:foreground "white"))))
 '(diredfl-file-suffix ((((class color) (min-colors 257)) (:foreground "#6b7a87")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(diredfl-flag-mark ((((class color) (min-colors 257)) (:foreground "#EBBF83" :background "#46433d" :weight bold)) (((class color) (min-colors 256)) (:foreground "#EEBB88" :background nil :weight bold)) (((class color) (min-colors 16)) (:foreground "yellow" :background nil :weight bold))))
 '(diredfl-flag-mark-line ((((class color) (min-colors 257)) (:background "#313434")) (((class color) (min-colors 256)) (:background nil)) (((class color) (min-colors 16)) (:background nil))))
 '(diredfl-ignored-file-name ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(diredfl-link-priv ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(diredfl-no-priv ((((class color) (min-colors 257)) (:foreground "#A0B3C5")) (((class color) (min-colors 256)) (:foreground "#AABBCC")) (((class color) (min-colors 16)) (:foreground "white"))))
 '(diredfl-number ((((class color) (min-colors 257)) (:foreground "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(diredfl-other-priv ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(diredfl-rare-priv ((((class color) (min-colors 257)) (:foreground "#A0B3C5")) (((class color) (min-colors 256)) (:foreground "#AABBCC")) (((class color) (min-colors 16)) (:foreground "white"))))
 '(diredfl-read-priv ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(diredfl-symlink ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(diredfl-tagged-autofile-name ((((class color) (min-colors 257)) (:foreground "#56697A")) (((class color) (min-colors 256)) (:foreground "#556677")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(diredfl-write-priv ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(doom-modeline-bar-inactive ((t (:background nil))))
 '(evil-ex-info ((((class color) (min-colors 257)) (:foreground "#D95468" :slant italic)) (((class color) (min-colors 256)) (:foreground "#ff6655" :slant italic)) (((class color) (min-colors 16)) (:foreground "red" :slant italic))))
 '(evil-ex-search ((((class color) (min-colors 257)) (:background "#5EC4FF" :foreground "#10151C" :weight bold)) (((class color) (min-colors 256)) (:background "#55CCFF" :foreground "black" :weight bold)) (((class color) (min-colors 16)) (:background "brightblue" :foreground "black" :weight bold))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 257)) (:background "#10151C" :foreground "#D95468" :strike-through t :weight bold)) (((class color) (min-colors 256)) (:background "black" :foreground "#ff6655" :strike-through t :weight bold)) (((class color) (min-colors 16)) (:background "black" :foreground "red" :strike-through t :weight bold))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 257)) (:background "#10151C" :foreground "#8BD49C" :weight bold)) (((class color) (min-colors 256)) (:background "black" :foreground "#99bb66" :weight bold)) (((class color) (min-colors 16)) (:background "black" :foreground "green" :weight bold))))
 '(evil-snipe-first-match-face ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :background "#718CA1" :weight bold)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :background "#7788AA" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :background "blue" :weight bold))))
 '(evil-snipe-matches-face ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :underline t :weight bold)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :underline t :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :underline t :weight bold))))
 '(evil-goggles-default-face ((t (:extend t :background "#2a2a2a" :distant-foreground "#5eb2f2" :foreground "#5eb2f2"))))
 '(flycheck-error ((((class color) (min-colors 257)) (:underline (:style wave :color "#D95468"))) (((class color) (min-colors 256)) (:underline (:style wave :color "#ff6655"))) (((class color) (min-colors 16)) (:underline (:style wave :color "red")))))
 '(flycheck-warning ((((class color) (min-colors 257)) (:underline (:style wave :color "#EBBF83"))) (((class color) (min-colors 256)) (:underline (:style wave :color "#EEBB88"))) (((class color) (min-colors 16)) (:underline (:style wave :color "yellow")))))
 '(flycheck-info ((((class color) (min-colors 257)) (:underline (:style wave :color "#8BD49C"))) (((class color) (min-colors 256)) (:underline (:style wave :color "#99bb66"))) (((class color) (min-colors 16)) (:underline (:style wave :color "green")))))
 '(flycheck-fringe-error ((((class color) (min-colors 257)) (:inherit fringe :foreground "#D95468")) (((class color) (min-colors 256)) (:inherit fringe :foreground "#ff6655")) (((class color) (min-colors 16)) (:inherit fringe :foreground "red"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 257)) (:inherit fringe :foreground "#EBBF83")) (((class color) (min-colors 256)) (:inherit fringe :foreground "#EEBB88")) (((class color) (min-colors 16)) (:inherit fringe :foreground "yellow"))))
 '(flycheck-fringe-info ((((class color) (min-colors 257)) (:inherit fringe :foreground "#8BD49C")) (((class color) (min-colors 256)) (:inherit fringe :foreground "#99bb66")) (((class color) (min-colors 16)) (:inherit fringe :foreground "green"))))
 '(flyspell-incorrect ((((class color) (min-colors 257)) (:underline (:style wave :color "#D95468") :inherit unspecified)) (((class color) (min-colors 256)) (:underline (:style wave :color "#ff6655") :inherit unspecified)) (((class color) (min-colors 16)) (:underline (:style wave :color "red") :inherit unspecified))))
 '(flyspell-duplicate ((((class color) (min-colors 257)) (:underline (:style wave :color "#EBBF83") :inherit unspecified)) (((class color) (min-colors 256)) (:underline (:style wave :color "#EEBB88") :inherit unspecified)) (((class color) (min-colors 16)) (:underline (:style wave :color "yellow") :inherit unspecified))))
 '(git-commit-summary ((((class color) (min-colors 257)) (:foreground "#539AFC")) (((class color) (min-colors 256)) (:foreground "#5599FF")) (((class color) (min-colors 16)) (:foreground "blue"))))
 '(git-commit-overlong-summary ((((class color) (min-colors 257)) (:inherit error :background "#10151C" :slant italic :weight bold)) (((class color) (min-colors 256)) (:inherit error :background "black" :slant italic :weight bold)) (((class color) (min-colors 16)) (:inherit error :background "black" :slant italic :weight bold))))
 '(git-commit-nonempty-second-line ((t (:inherit git-commit-overlong-summary))))
 '(git-commit-keyword ((((class color) (min-colors 257)) (:foreground "#70E1E8" :slant italic)) (((class color) (min-colors 256)) (:foreground "#77EEEE" :slant italic)) (((class color) (min-colors 16)) (:foreground "brightcyan" :slant italic))))
 '(git-commit-pseudo-header ((((class color) (min-colors 257)) (:foreground "#707b86" :slant italic)) (((class color) (min-colors 256)) (:foreground "#ff8c7f" :slant italic)) (((class color) (min-colors 16)) (:foreground "red" :slant italic))))
 '(git-commit-known-pseudo-header ((((class color) (min-colors 257)) (:foreground "#707b86" :weight bold :slant italic)) (((class color) (min-colors 256)) (:foreground "#ff8c7f" :weight bold :slant italic)) (((class color) (min-colors 16)) (:foreground "red" :weight bold :slant italic))))
 '(git-commit-comment-branch-local ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(git-commit-comment-branch-remote ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(git-commit-comment-detached ((((class color) (min-colors 257)) (:foreground "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(git-commit-comment-heading ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(git-commit-comment-file ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(git-commit-comment-action ((t (:inherit (bold)))))
 '(highlight-quoted-symbol ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(highlight-quoted-quote ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(highlight-numbers-number ((((class color) (min-colors 257)) (:inherit bold :foreground "#E27E8D")) (((class color) (min-colors 256)) (:inherit bold :foreground "#EE7788")) (((class color) (min-colors 16)) (:inherit bold :foreground "magenta"))))
 '(hl-todo ((((class color) (min-colors 257)) (:foreground "#D95468" :weight bold)) (((class color) (min-colors 256)) (:foreground "#ff6655" :weight bold)) (((class color) (min-colors 16)) (:foreground "red" :weight bold))))
 '(ivy-current-match ((((class color) (min-colors 257)) (:background "#28323B" :distant-foreground nil :extend t)) (((class color) (min-colors 256)) (:background "#223333" :distant-foreground nil :extend t)) (((class color) (min-colors 16)) (:background "brightblack" :distant-foreground nil :extend t))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 257)) (:background nil :foreground "#5b6874" :weight light)) (((class color) (min-colors 256)) (:background nil :foreground "#ff7b6c" :weight light)) (((class color) (min-colors 16)) (:background nil :foreground "red" :weight light))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :weight bold)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 257)) (:inherit ivy-minibuffer-match-face-2 :foreground "#FB8496" :weight semi-bold)) (((class color) (min-colors 256)) (:inherit ivy-minibuffer-match-face-2 :foreground "#FB8496" :weight semi-bold)) (((class color) (min-colors 16)) (:inherit ivy-minibuffer-match-face-2 :foreground "green" :weight semi-bold))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 257)) (:inherit ivy-minibuffer-match-face-2 :foreground "#EBBF83" :weight semi-bold)) (((class color) (min-colors 256)) (:inherit ivy-minibuffer-match-face-2 :foreground "#EEBB88" :weight semi-bold)) (((class color) (min-colors 16)) (:inherit ivy-minibuffer-match-face-2 :foreground "yellow" :weight semi-bold))))
 '(ivy-minibuffer-match-highlight ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(ivy-highlight-face ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(ivy-confirm-face ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(ivy-match-required-face ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(ivy-virtual ((((class color) (min-colors 257)) (:inherit italic :foreground "#707b86")) (((class color) (min-colors 256)) (:inherit italic :foreground "#ff8c7f")) (((class color) (min-colors 16)) (:inherit italic :foreground "red"))))
 '(ivy-modified-buffer ((((class color) (min-colors 257)) (:inherit bold :foreground "#D98E48")) (((class color) (min-colors 256)) (:inherit bold :foreground "#dd8844")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightred"))))
 '(magit-bisect-bad ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(magit-bisect-good ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(magit-bisect-skip ((((class color) (min-colors 257)) (:foreground "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(magit-blame-date ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(magit-blame-heading ((((class color) (min-colors 257)) (:foreground "#D98E48" :background "#28323B" :extend t)) (((class color) (min-colors 256)) (:foreground "#dd8844" :background "#223333" :extend t)) (((class color) (min-colors 16)) (:foreground "brightred" :background "brightblack" :extend t))))
 '(magit-branch-current ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(magit-branch-local ((((class color) (min-colors 257)) (:foreground "#70E1E8")) (((class color) (min-colors 256)) (:foreground "#77EEEE")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(magit-branch-remote ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(magit-cherry-equivalent ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(magit-cherry-unmatched ((((class color) (min-colors 257)) (:foreground "#70E1E8")) (((class color) (min-colors 256)) (:foreground "#77EEEE")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(magit-diff-added ((((class color) (min-colors 257)) (:foreground "#6fa97c" :background "#283637" :extend t)) (((class color) (min-colors 256)) (:foreground "#7a9551" :background nil :extend t)) (((class color) (min-colors 16)) (:foreground "green" :background nil :extend t))))
 '(magit-diff-added-highlight ((((class color) (min-colors 257)) (:foreground "#8BD49C" :background "#334842" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#99bb66" :background nil :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "green" :background nil :weight bold :extend t))))
 '(magit-diff-base ((((class color) (min-colors 257)) (:foreground "#ad7139" :background "#2f2f2e" :extend t)) (((class color) (min-colors 256)) (:foreground "#b06c36" :background nil :extend t)) (((class color) (min-colors 16)) (:foreground "brightred" :background nil :extend t))))
 '(magit-diff-base-highlight ((((class color) (min-colors 257)) (:foreground "#D98E48" :background "#423a31" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#dd8844" :background nil :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightred" :background nil :weight bold :extend t))))
 '(magit-diff-context ((((class color) (min-colors 257)) (:foreground "#606b76" :background "#1D252C" :extend t)) (((class color) (min-colors 256)) (:foreground "#65707a" :background nil :extend t)) (((class color) (min-colors 16)) (:foreground "white" :background nil :extend t))))
 '(magit-diff-context-highlight ((((class color) (min-colors 257)) (:foreground "#A0B3C5" :background "#181E24" :extend t)) (((class color) (min-colors 256)) (:foreground "#AABBCC" :background nil :extend t)) (((class color) (min-colors 16)) (:foreground "white" :background nil :extend t))))
 '(magit-diff-file-heading ((((class color) (min-colors 257)) (:foreground "#A0B3C5" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#AABBCC" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "white" :weight bold :extend t))))
 '(magit-diff-file-heading-selection ((((class color) (min-colors 257)) (:foreground "#E27E8D" :background "#718CA1" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#EE7788" :background "#7788AA" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "magenta" :background "blue" :weight bold :extend t))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 257)) (:foreground "#728CA0" :background "#28323B" :weight normal)) (((class color) (min-colors 256)) (:foreground "#7788AA" :background "#223333" :weight normal)) (((class color) (min-colors 16)) (:foreground "brightwhite" :background "brightblack" :weight normal))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 257)) (:foreground "#A0B3C5" :background "#384551" :weight bold)) (((class color) (min-colors 256)) (:foreground "#AABBCC" :background "#334455" :weight bold)) (((class color) (min-colors 16)) (:foreground "white" :background "brightblack" :weight bold))))
 '(magit-diff-removed ((((class color) (min-colors 257)) (:foreground "#ad4353" :background "#39353f" :extend t)) (((class color) (min-colors 256)) (:foreground "#cc5144" :background "#383836" :extend t)) (((class color) (min-colors 16)) (:foreground "red" :background "red" :extend t))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 257)) (:foreground "#D95468" :background "#4b3844" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#ff6655" :background "#4e3d39" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "red" :background "red" :weight bold :extend t))))
 '(magit-diff-lines-heading ((((class color) (min-colors 257)) (:foreground "#EBBF83" :background "#D95468" :extend t :extend t)) (((class color) (min-colors 256)) (:foreground "#EEBB88" :background "#ff6655" :extend t :extend t)) (((class color) (min-colors 16)) (:foreground "yellow" :background "red" :extend t :extend t))))
 '(magit-diffstat-added ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(magit-diffstat-removed ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(magit-dimmed ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(magit-hash ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(magit-header-line ((((class color) (min-colors 257)) (:background "#718CA1" :foreground "#9CAABB" :weight bold :box (:line-width 3 :color "#718CA1"))) (((class color) (min-colors 256)) (:background "#7788AA" :foreground "#99AABB" :weight bold :box (:line-width 3 :color "#7788AA"))) (((class color) (min-colors 16)) (:background "blue" :foreground "white" :weight bold :box (:line-width 3 :color "blue")))))
 '(magit-log-author ((((class color) (min-colors 257)) (:foreground "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(magit-log-date ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(magit-log-graph ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(magit-process-ng ((t (:inherit error))))
 '(magit-process-ok ((t (:inherit success))))
 '(magit-reflog-amend ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(magit-reflog-checkout ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(magit-reflog-commit ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(magit-reflog-merge ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(magit-reflog-other ((((class color) (min-colors 257)) (:foreground "#70E1E8")) (((class color) (min-colors 256)) (:foreground "#77EEEE")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(magit-reflog-rebase ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(magit-reflog-remote ((((class color) (min-colors 257)) (:foreground "#70E1E8")) (((class color) (min-colors 256)) (:foreground "#77EEEE")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(magit-reflog-reset ((t (:inherit error))))
 '(magit-refname ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(magit-section-heading ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold :extend t))))
 '(magit-section-heading-selection ((((class color) (min-colors 257)) (:foreground "#D98E48" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#dd8844" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightred" :weight bold :extend t))))
 '(magit-section-highlight ((t (:inherit hl-line))))
 '(magit-sequence-drop ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(magit-sequence-head ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(magit-sequence-part ((((class color) (min-colors 257)) (:foreground "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(magit-sequence-stop ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(magit-signature-bad ((t (:inherit error))))
 '(magit-signature-error ((t (:inherit error))))
 '(magit-signature-expired ((((class color) (min-colors 257)) (:foreground "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(magit-signature-good ((t (:inherit success))))
 '(magit-signature-revoked ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(magit-signature-untrusted ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(magit-tag ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(magit-filename ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(magit-section-secondary-heading ((((class color) (min-colors 257)) (:foreground "#B62D65" :weight bold :extend t)) (((class color) (min-colors 256)) (:foreground "#BB2266" :weight bold :extend t)) (((class color) (min-colors 16)) (:foreground "brightmagenta" :weight bold :extend t))))
 '(persp-face-lighter-default ((((class color) (min-colors 257)) (:foreground "#5EC4FF" :weight bold)) (((class color) (min-colors 256)) (:foreground "#55CCFF" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(persp-face-lighter-buffer-not-in-persp ((((class color) (min-colors 257)) (:foreground "#707b86")) (((class color) (min-colors 256)) (:foreground "#ff8c7f")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(persp-face-lighter-nil-persp ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(popup-face ((t (:inherit tooltip))))
 '(popup-tip-face ((((class color) (min-colors 257)) (:inherit popup-face :foreground "#B62D65" :background "#10151C")) (((class color) (min-colors 256)) (:inherit popup-face :foreground "#BB2266" :background "black")) (((class color) (min-colors 16)) (:inherit popup-face :foreground "brightmagenta" :background "black"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 257)) (:foreground "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 257)) (:foreground "#33CED8")) (((class color) (min-colors 256)) (:foreground "#33CCDD")) (((class color) (min-colors 16)) (:foreground "brightgreen"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 257)) (:foreground "#D95468" :weight bold :inverse-video t)) (((class color) (min-colors 256)) (:foreground "#ff6655" :weight bold :inverse-video t)) (((class color) (min-colors 16)) (:foreground "red" :weight bold :inverse-video t))))
 '(rainbow-delimiters-mismatched-face ((t (:inherit rainbow-delimiters-unmatched-face))))
 '(reb-match-0 ((((class color) (min-colors 257)) (:foreground "#D98E48" :inverse-video t)) (((class color) (min-colors 256)) (:foreground "#dd8844" :inverse-video t)) (((class color) (min-colors 16)) (:foreground "brightred" :inverse-video t))))
 '(reb-match-1 ((((class color) (min-colors 257)) (:foreground "#E27E8D" :inverse-video t)) (((class color) (min-colors 256)) (:foreground "#EE7788" :inverse-video t)) (((class color) (min-colors 16)) (:foreground "magenta" :inverse-video t))))
 '(reb-match-2 ((((class color) (min-colors 257)) (:foreground "#8BD49C" :inverse-video t)) (((class color) (min-colors 256)) (:foreground "#99bb66" :inverse-video t)) (((class color) (min-colors 16)) (:foreground "green" :inverse-video t))))
 '(reb-match-3 ((((class color) (min-colors 257)) (:foreground "#EBBF83" :inverse-video t)) (((class color) (min-colors 256)) (:foreground "#EEBB88" :inverse-video t)) (((class color) (min-colors 16)) (:foreground "yellow" :inverse-video t))))
 '(sp-pair-overlay-face ((((class color) (min-colors 257)) (:background "#28323B")) (((class color) (min-colors 256)) (:background "#223333")) (((class color) (min-colors 16)) (:background "brightblack"))))
 '(smerge-base ((((class color) (min-colors 257)) (:background "#2a4456")) (((class color) (min-colors 256)) (:background nil)) (((class color) (min-colors 16)) (:background nil))))
 '(smerge-markers ((((class color) (min-colors 257)) (:background "#41505E" :foreground "#1D252C" :distant-foreground "#A0B3C5" :weight bold)) (((class color) (min-colors 256)) (:background "#ff6655" :foreground nil :distant-foreground "#AABBCC" :weight bold)) (((class color) (min-colors 16)) (:background "red" :foreground nil :distant-foreground "white" :weight bold))))
 '(smerge-refined-added ((t (:inherit diff-added :inverse-video t))))
 '(smerge-refined-removed ((t (:inherit diff-removed :inverse-video t))))
 '(swiper-line-face ((((class color) (min-colors 257)) (:background "#5EC4FF" :foreground "#10151C")) (((class color) (min-colors 256)) (:background "#55CCFF" :foreground "black")) (((class color) (min-colors 16)) (:background "brightblue" :foreground "black"))))
 '(swiper-match-face-1 ((((class color) (min-colors 257)) (:inherit unspecified :background "#10151C" :foreground "#56697A")) (((class color) (min-colors 256)) (:inherit unspecified :background "black" :foreground "#556677")) (((class color) (min-colors 16)) (:inherit unspecified :background "black" :foreground "brightblack"))))
 '(swiper-match-face-2 ((((class color) (min-colors 257)) (:inherit unspecified :background "#D98E48" :foreground "#10151C" :weight bold)) (((class color) (min-colors 256)) (:inherit unspecified :background "#dd8844" :foreground "black" :weight bold)) (((class color) (min-colors 16)) (:inherit unspecified :background "brightred" :foreground "black" :weight bold))))
 '(swiper-match-face-3 ((((class color) (min-colors 257)) (:inherit unspecified :background "#E27E8D" :foreground "#10151C" :weight bold)) (((class color) (min-colors 256)) (:inherit unspecified :background "#EE7788" :foreground "black" :weight bold)) (((class color) (min-colors 16)) (:inherit unspecified :background "magenta" :foreground "black" :weight bold))))
 '(swiper-match-face-4 ((((class color) (min-colors 257)) (:inherit unspecified :background "#8BD49C" :foreground "#10151C" :weight bold)) (((class color) (min-colors 256)) (:inherit unspecified :background "#99bb66" :foreground "black" :weight bold)) (((class color) (min-colors 16)) (:inherit unspecified :background "green" :foreground "black" :weight bold))))
 '(which-func ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(which-key-key-face ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(which-key-group-description-face ((((class color) (min-colors 257)) (:foreground "#B62D65")) (((class color) (min-colors 256)) (:foreground "#BB2266")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(which-key-command-description-face ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(which-key-local-map-description-face ((((class color) (min-colors 257)) (:foreground "#E27E8D")) (((class color) (min-colors 256)) (:foreground "#EE7788")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(yas-field-highlight-face ((t (:inherit match))))
 '(outline-1 ((t (:extend t :foreground "#5eb2f2" :weight bold))))
 '(outline-2 ((t (:extend t :foreground "#A6C3F6" :weight bold))))
 '(outline-3 ((t (:extend t :foreground "#CCCCCC" :weight bold))))
 '(outline-4 ((t (:extend t :foreground "#FDDC87" :weight bold))))
 '(outline-5 ((t (:extend t :foreground "#DCCC78" :weight bold))))
 '(outline-6 ((t (:extend t :foreground "#BD9800" :weight bold))))
 '(outline-7 ((t (:extend t :foreground "#FB8496" :weight bold))))
 '(outline-8 ((t (:extend t :foreground "#FF8833" :weight bold))))
 '(org-archived ((((class color) (min-colors 257)) (:foreground "#707b86")) (((class color) (min-colors 256)) (:foreground "#ff8c7f")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(org-block ((t (:extend t :background "#212537"))))
 '(org-block-begin-line ((t (:extend t :background "#2f354f" :foreground "#AAAAAA"))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-checkbox ((t (:inherit org-todo))))
 '(org-checkbox-statistics-done ((t (:inherit org-done))))
 '(org-checkbox-statistics-todo ((t (:inherit org-todo))))
 '(org-code ((((class color) (min-colors 257)) (:foreground "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(org-date ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(org-default ((t (:inherit variable-pitch))))
 '(org-document-info ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(org-document-title ((t (:foreground "#5EC4FF" :weight bold :height 1.4))))
 '(org-done ((t (:inherit org-headline-done :bold inherit))))
 '(org-ellipsis ((((class color) (min-colors 257)) (:underline nil :background nil :foreground "#41505E")) (((class color) (min-colors 256)) (:underline nil :background nil :foreground "#ff6655")) (((class color) (min-colors 16)) (:underline nil :background nil :foreground "red"))))
 '(org-footnote ((((class color) (min-colors 257)) (:foreground "#D98E48")) (((class color) (min-colors 256)) (:foreground "#dd8844")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(org-formula ((((class color) (min-colors 257)) (:foreground "#70E1E8")) (((class color) (min-colors 256)) (:foreground "#77EEEE")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(org-headline-done ((((class color) (min-colors 257)) (:foreground "#56697A")) (((class color) (min-colors 256)) (:foreground "#556677")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(org-hide ((t (:foreground "#010517"))))
 '(org-list-dt ((((class color) (min-colors 257)) (:foreground "#5EC4FF")) (((class color) (min-colors 256)) (:foreground "#55CCFF")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(org-meta-line ((((class color) (min-colors 257)) (:foreground "#707b86")) (((class color) (min-colors 256)) (:foreground "#ff8c7f")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(org-priority ((((class color) (min-colors 257)) (:foreground "#D95468")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(org-property-value ((((class color) (min-colors 257)) (:foreground "#707b86")) (((class color) (min-colors 256)) (:foreground "#ff8c7f")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(org-quote ((((class color) (min-colors 257)) (:background "#28323B" :slant italic :extend t)) (((class color) (min-colors 256)) (:background "#223333" :slant italic :extend t)) (((class color) (min-colors 16)) (:background "brightblack" :slant italic :extend t))))
 '(org-special-keyword ((((class color) (min-colors 257)) (:foreground "#707b86")) (((class color) (min-colors 256)) (:foreground "#ff8c7f")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(org-table ((t (:foreground "#ffa8b6"))))
 '(org-tag ((((class color) (min-colors 257)) (:foreground "#707b86" :weight normal)) (((class color) (min-colors 256)) (:foreground "#ff8c7f" :weight normal)) (((class color) (min-colors 16)) (:foreground "red" :weight normal))))
 '(org-latex-and-related ((((class color) (min-colors 257)) (:foreground "#9CAABB" :weight bold)) (((class color) (min-colors 256)) (:foreground "#99AABB" :weight bold)) (((class color) (min-colors 16)) (:foreground "white" :weight bold))))
 '(org-todo ((((class color) (min-colors 257)) (:foreground "#8BD49C" :bold inherit)) (((class color) (min-colors 256)) (:foreground "#99bb66" :bold inherit)) (((class color) (min-colors 16)) (:foreground "green" :bold inherit))))
 '(org-verbatim ((((class color) (min-colors 257)) (:foreground "#8BD49C")) (((class color) (min-colors 256)) (:foreground "#99bb66")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(org-warning ((((class color) (min-colors 257)) (:foreground "#EBBF83")) (((class color) (min-colors 256)) (:foreground "#EEBB88")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(org-agenda-done ((t (:inherit org-done))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(org-agenda-date ((t (:foreground "#A6C3F6" :weight ultra-bold))))
 '(org-agenda-date-today ((t (:foreground "#5eb2f2" :weight ultra-bold))))
 '(org-agenda-date-weekend ((t (:foreground "#AABFE6" :weight ultra-bold))))
 '(org-agenda-structure ((((class color) (min-colors 257)) (:foreground "#A0B3C5" :weight ultra-bold)) (((class color) (min-colors 256)) (:foreground "#AABBCC" :weight ultra-bold)) (((class color) (min-colors 16)) (:foreground "white" :weight ultra-bold))))
 '(org-agenda-clocking ((((class color) (min-colors 257)) (:background "#2a4456")) (((class color) (min-colors 256)) (:background nil)) (((class color) (min-colors 16)) (:background nil))))
 '(org-upcoming-deadline ((((class color) (min-colors 257)) (:foreground "#8596a6")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(org-upcoming-distant-deadline ((((class color) (min-colors 257)) (:foreground "#5e6c78")) (((class color) (min-colors 256)) (:foreground nil)) (((class color) (min-colors 16)) (:foreground nil))))
 '(org-scheduled ((((class color) (min-colors 257)) (:foreground "#A0B3C5")) (((class color) (min-colors 256)) (:foreground "#AABBCC")) (((class color) (min-colors 16)) (:foreground "white"))))
 '(org-scheduled-today ((((class color) (min-colors 257)) (:foreground "#7FA0B7")) (((class color) (min-colors 256)) (:foreground "#77AABB")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(org-scheduled-previously ((((class color) (min-colors 257)) (:foreground "#9CAABB")) (((class color) (min-colors 256)) (:foreground "#99AABB")) (((class color) (min-colors 16)) (:foreground "white"))))
 '(org-time-grid ((((class color) (min-colors 257)) (:foreground "#41505E")) (((class color) (min-colors 256)) (:foreground "#ff6655")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(org-sexp-date ((((class color) (min-colors 257)) (:foreground "#A0B3C5")) (((class color) (min-colors 256)) (:foreground "#AABBCC")) (((class color) (min-colors 16)) (:foreground "white"))))
 '(doom-modeline-bar ((t (:background "#5eb2f2"))))
 '(tab-bar ((((class color) (min-colors 257)) (:background "#181E24" :foreground "#181E24")) (((class color) (min-colors 256)) (:background nil :foreground nil)) (((class color) (min-colors 16)) (:background nil :foreground nil))))
 '(tab-bar-tab ((((class color) (min-colors 257)) (:background "#1D252C" :foreground "#A0B3C5")) (((class color) (min-colors 256)) (:background nil :foreground "#AABBCC")) (((class color) (min-colors 16)) (:background nil :foreground "white"))))
 '(tab-bar-tab-inactive ((((class color) (min-colors 257)) (:background "#181E24" :foreground "#728CA0")) (((class color) (min-colors 256)) (:background nil :foreground "#7788AA")) (((class color) (min-colors 16)) (:background nil :foreground "brightwhite"))))
 '(show-paren-match ((t (:background "#30353C" :foreground "#D95468" :weight ultra-bold))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:foreground "#10151C" :background "#D95468" :weight ultra-bold)) (((class color) (min-colors 256)) (:foreground "black" :background "#ff6655" :weight ultra-bold)) (((class color) (min-colors 16)) (:foreground "black" :background "red" :weight ultra-bold))))
 '(sp-show-pair-match-face ((t (:background "#30353C" :foreground "#D95468" :weight ultra-bold))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 257)) (:foreground "#10151C" :background "#D95468" :weight ultra-bold)) (((class color) (min-colors 256)) (:foreground "black" :background "#ff6655" :weight ultra-bold)) (((class color) (min-colors 16)) (:foreground "black" :background "red" :weight ultra-bold))))
 '(smerge-upper ((((class color) (min-colors 257)) (:background "#4b3844")) (((class color) (min-colors 256)) (:background "#4e3d39")) (((class color) (min-colors 16)) (:background "red"))))
 '(smerge-lower ((((class color) (min-colors 257)) (:background "#334842")) (((class color) (min-colors 256)) (:background nil)) (((class color) (min-colors 16)) (:background nil))))
 '(default ((t (:background "#151926" :foreground "#AAAAAA")))))

(provide-theme 'cornell)
